### ISSUE TITLE
Expand OverPass Query Highlighter to ways (street, building)

### ISSUE THREAD

**Issue by tordans** [wtimme/OSM-Completionist#19]
ATM, only nodes are highlighted. The feature is also interesting for areas and lines.

Example:
- `highway=* and surface is null` for all streets that are missing a surface
- `building=* and "roof:shape" is null` for all buildings that are missing roof-tagging

![Bildschirmfoto 2020-01-03 um 04 22 31 Kopie](https://user-images.githubusercontent.com/111561/71705636-0ef43b80-2de1-11ea-9952-f3839351bc58.jpg)
![Bildschirmfoto 2020-01-03 um 04 21 56 Kopie](https://user-images.githubusercontent.com/111561/71705637-0ef43b80-2de1-11ea-938f-21b6b0490d31.jpg)

**Comment by wtimme** [comment]
Thanks for the suggestion, @tordans!

This proved easier than expected, since the parser is type-agnostic and works with ways/buildings the same it works with objects.

Here's a preview:

![osm-completionist-way-highlighting](https://user-images.githubusercontent.com/1681085/71734185-41368500-2e43-11ea-9c75-5e17a36108dd.png)

I've also submitted a new TestFlight build that includes these changes. Please have a look and let me know how it works.

One thing that I noticed while testing is that we need to be able to have multiple quests/queries active at the same time (cp. #21). Switching back and forth between them gets tedious after some time.

**Comment by tordans** [comment]
A quick test worked great. Thanks!
