### ISSUE TITLE
Congratulation message links to Go Map!! in the App Store

### ISSUE THREAD

**Issue by habi** [wtimme/OSM-Completionist#48]
I've uploaded +10 change sets with OSM-Completionist, then I get a congratulation message (attached).
The *I'll do it* button links to [Go Map!!](in the App Store).
This should probably be changed :)

![IMG_2950](https://user-images.githubusercontent.com/1651235/73397611-3658fe00-42e4-11ea-82b2-1acc5b5b354e.PNG)

**Comment by wtimme** [comment]
Hey @habi,

Thanks for the feedback! Indeed - it uses the App ID of _Go Map!!_. I'll need to release the app in order to get ratings.

Since "OSM Completionist" is not available on the App Store yet (#49), the user is not able to add reviews.

I like the functionality, and I would like to have it active once the app is released, but for now, I think the easiest (MVP) approach is to remove it. We can retrieve it later again from the Git history.
