### ISSUE TITLE
Delete Relation Membership

### ISSUE THREAD

**Issue by DerKarlos** [wtimme/OSM-Completionist#69]
# User Story
I could not solve a fixme: a tourist sign was placed twice in OSM.
And both have been part of a relation.
I could view the relation and its members but not delete a member

> As [stakeholder], I want [action], so that [benefit]
Deleting of a member(ship) should be possible

# Unhappy Cases

Editing relations may be critical, especially for beginners.
So an extra warning may pop up

**Comment by wtimme** [comment]
Hey @DerKarlos,

Thanks for the input! OSM-Completionist is a fork of [GoMap][1] with only a couple of additions that make it easier to "complete" the map by answering question.

Your request sounds like something that would be better-suited in the parent application, GoMap. It would eventually end up on OSM-Completionist (when merging the `master` of GoMap again), but it would benefit the _whole_ GoMap community.

For this reason, I'm going to close this issue and would like to ask you to [create a new one over at GoMap's repository][2]. That way, you'll get even more feedback and support for it. Thanks again for your contribution!

[1]: https://github.com/bryceco/GoMap
[2]: https://github.com/bryceco/GoMap/issues/new?title=Delete%20Relation%20Membership

**Comment by bryceco** [comment]
Depending on the type of deletion it may be the case that Go Map!! will support it, but not necessarily. There will probably exist situations where the quest should not be displayed because fixing the problem will require a more elaborate fix.

Simply deleting a member of a route or turn restriction will likely be the wrong fix. Deleting a boundary or multipolygon member is probably okay, but there are still edge cases where the intent is to delete a sign (like in this case), but the sign happens to also be a node in an unrelated way and deleting it changes the geometry. If you want to be conservative you should not display quests that require deleting way or relation members. Alternately in those cases you could untag it instead.

**Comment by DerKarlos** [comment]
In this case it was an KeepRight/fixit "exact position" at a info sign. The info was one of a line, connected by a relation, no way included. But the sign was twice in the relation (may be there had been two once) To delete one of them could be support, I assume.
To decide if the quest is displayed will be a good part of work. Thank you for all your efforts anyway.
