### ISSUE TITLE
Has OSM-Completionist Been Resurrected?

### ISSUE THREAD

**Issue by pqhf5kd** [wtimme/OSM-Completionist#74]
Hey Wtimme
I see that you've been pushing commits to OSM-Completionist. Have you revived the project? 
OSM-Surveyor hasn't been updated since August.

**Comment by wtimme** [comment]
Hey @pqhf5kd,

Thanks for your interest in the project! Short answer: No, it is still not being maintained.

Long answer: One of the things that caused me a lot of time during the development of this GoMap fork was the fact that I was using the same project file as the main project, resulting in a lot of merge conflicts almost every time I merged the `upstream` repository into mine. I recently came across [XcodeGen][1], a tool for generating Xcode projects from a Yaml file. I saw the opportunity to use it in order to get rid of these nasty merge conflicts and gave it a try with OSM-Completionist.

I do not actively develop this project right now, and as you already pointed out, OSM-Surveyor has not been updated either. I was recently in touch with westnordost regarding streetcomplete/StreetComplete#1892, and I think that porting the Android version over might be the more sustainable solution here, since we could end up leveraging a lot of the existing (Kotlin-) logic.

I hope that answers your question. Again, thanks for your interest in the project! If you wanted to contribute to a similar functionality for GoMap, feel free to checkout and contribute to bryceco/GoMap#438, which is supposed to be a step towards more generic and customizable interaction pattern with objects on the map.

Have a nice day!

[1]: https://github.com/yonaskolb/XcodeGen
